"""Fachada de reglas de señalización para mantener imports compatibles."""

# Las reglas se han dividido por responsabilidad, pero este módulo conserva los
# nombres antiguos para no obligar a cambiar imports en tests, apps o notebooks.
from .content_signals import (
    adjuntos_sospechosos,
    asunto_sospechoso,
    contiene_palabras_urgentes,
    contiene_referencia_archivo,
    saludo_generico,
    solicitud_datos_credenciales,
)
from .header_signals import (
    cabecera_spoofing,
    dkim_mal_formado,
    dmarc_fallido,
    extraer_dominio_spf,
    incoherencia_remitente,
    mensaje_firmado_o_cifrado,
    mensaje_id_sospechoso,
    nombre_display_engano,
    obtener_cabecera,
    obtener_dominio_desde_email,
    obtener_email_desde_cabecera,
    remitente_marca_engano,
    tiene_fallo_autenticacion,
    tiene_recibidos_sospechosos,
    tiene_reply_to_diferente,
)
from .html_signals import (
    contiene_formulario_html,
    contiene_html_sospechoso,
    contiene_javascript_redireccion,
    contiene_meta_refresh,
    formulario_action_sospechoso,
    texto_enlace_distinto,
)
from .url_utils import (
    contiene_punycode_o_unicode,
    dominios_sospechosos,
    enlace_shortener,
    es_dominio_confuso,
    es_dominio_listado_negro,
    es_ip_enlace,
    extraer_dominio,
    extraer_urls,
    texto_contiene_dominio,
    tiene_parametros_sospechosos_url,
)

__all__ = [
    "adjuntos_sospechosos",
    "asunto_sospechoso",
    "cabecera_spoofing",
    "contiene_formulario_html",
    "contiene_html_sospechoso",
    "contiene_javascript_redireccion",
    "contiene_meta_refresh",
    "contiene_palabras_urgentes",
    "contiene_punycode_o_unicode",
    "contiene_referencia_archivo",
    "dkim_mal_formado",
    "dmarc_fallido",
    "dominios_sospechosos",
    "enlace_shortener",
    "es_dominio_confuso",
    "es_dominio_listado_negro",
    "es_ip_enlace",
    "extraer_dominio",
    "extraer_dominio_spf",
    "extraer_urls",
    "formulario_action_sospechoso",
    "incoherencia_remitente",
    "mensaje_firmado_o_cifrado",
    "mensaje_id_sospechoso",
    "nombre_display_engano",
    "obtener_cabecera",
    "obtener_dominio_desde_email",
    "obtener_email_desde_cabecera",
    "remitente_marca_engano",
    "saludo_generico",
    "solicitud_datos_credenciales",
    "texto_contiene_dominio",
    "texto_enlace_distinto",
    "tiene_fallo_autenticacion",
    "tiene_parametros_sospechosos_url",
    "tiene_recibidos_sospechosos",
    "tiene_reply_to_diferente",
]
